// SPDX-FileCopyrightText: 2026 北京京微资易科技有限公司 and AI WorkDeck contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
// Real LOWA model: ephemeral semantic suggestions are inert until safe acceptance.
import assert from 'node:assert/strict'
import JSZip from 'jszip'
import { preflight, loadPuppeteer, startServer, launchBrowser, openEditor } from './_boot.mjs'

const debug = `debug_writing_readonly(p) { comparisonModel = p.enabled ? xModel : null; return {success:true}; },`
preflight()
const server = await startServer({ patchServed(url, bytes) {
  if (url === '/office_thread.js') return Buffer.from(bytes.toString().replace('const EXEC = {', 'const EXEC = {\n' + debug))
  if (/^\/assets\/editor-.*\.js$/.test(url)) return Buffer.from(bytes.toString().replace(/(['"])get_hyperlink_at_cursor\1/, m => m + ',"debug_writing_readonly"'))
  return bytes
} })
const browser = await launchBrowser(await loadPuppeteer())
try {
  const page = await openEditor(browser)
  const exec = (a, p = {}) => page.evaluate((a, p) => window.__loExecutor.executeCommand(a, p), a, p)
  const ok = async (a, p) => { const r = await exec(a, p); assert.equal(r.success, true, a + ': ' + JSON.stringify(r)); return r }
  const text = async () => (await ok('get_document_text', { __agent: true })).paragraphs.map(p => p.text).join('\n')
  const zip = new JSZip()
  zip.file('[Content_Types].xml', '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>')
  zip.file('_rels/.rels', '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>')
  zip.file('word/document.xml', '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p/></w:body></w:document>')
  const blank = Array.from(await zip.generateAsync({ type: 'uint8array' }))
  const reset = async (body = '采购方应') => {
    await ok('load_document', { name: 'semantic-synthetic.docx', bytes: blank })
    await ok('insert_at_cursor', { text: body })
  }
  const capture = () => ok('capture_writing_context', { radius: 160 })
  const accept = (ctx, value, extra = {}) => exec('accept_writing_suggestion', { token: ctx.token, revision: ctx.revision, text: value, ...extra })

  await reset()
  let ctx = await capture()
  assert.equal(ctx.before, '采购方应')
  assert.equal(typeof ctx.revision, 'number')
  assert.equal(ctx.available, true)
  assert.equal(await text(), '采购方应', 'capture/preview changes no document text')
  await ok('get_completion_context', { radius: 50 })
  assert.equal((await accept(ctx, '在十个工作日内提交意见。\n**下一段保持原样**')).success, true)
  assert.equal(await text(), '采购方应在十个工作日内提交意见。\n**下一段保持原样**', 'insert suffix only, split paragraphs, preserve literal markdown')
  assert.equal((await accept(ctx, '重复')).reason, 'stale')
  await ok('undo'); assert.equal(await text(), '采购方应', 'one undo restores all inserted paragraphs')
  await ok('redo'); assert.ok((await text()).endsWith('**下一段保持原样**'))
  console.log('PASS literal suffix/paragraph insertion, independent token, single undo/redo')

  await reset('前文十个工作日后文')
  await ok('find_navigate', { keyword: '十个工作日', direction: 'next' })
  ctx = await capture()
  assert.equal(ctx.hasSelection, true); assert.equal(ctx.available, true)
  assert.equal((await accept(ctx, '十五个工作日')).reason, 'selection-mismatch')
  assert.equal((await accept(ctx, '十五个工作日', { expectedSelection: '五个工作日' })).reason, 'selection-mismatch')
  assert.equal((await accept(ctx, '十五个工作日', { expectedSelection: ctx.selectedText })).success, true)
  assert.equal(await text(), '前文十五个工作日后文')
  await ok('undo'); assert.equal(await text(), '前文十个工作日后文')
  console.log('PASS exact selection replacement and one undo')

  await reset('第一段\n第二段')
  await ok('goto', { type: 'end' }); ctx = await capture()
  await ok('modify_paragraph', { index: 0, text: '另一段改动', __agent: true })
  await ok('goto', { type: 'end' })
  assert.equal((await accept(ctx, '旧建议')).reason, 'stale', 'unrelated paragraph edits invalidate whole-document semantic context')
  ctx = await capture(); await ok('goto', { type: 'start' })
  assert.equal((await accept(ctx, '错位')).reason, 'stale')
  await reset(); ctx = await capture(); await ok('insert_at_cursor', { text: '继续输入' })
  assert.equal((await accept(ctx, '迟到')).reason, 'stale')
  ctx = await capture(); await reset()
  assert.equal((await accept(ctx, '旧文件')).reason, 'stale')
  console.log('PASS revision, cursor, continued input and document-reload fences')

  ctx = await capture()
  assert.equal((await accept(ctx, 'x'.repeat(2001))).reason, 'invalid-suggestion')
  assert.equal((await accept(ctx, '')).reason, 'invalid-suggestion')
  assert.equal((await accept(ctx, '坏\u0000内容')).reason, 'invalid-suggestion')
  assert.equal((await accept(ctx, '错误版本', { revision: ctx.revision + 1 })).reason, 'stale')
  assert.equal((await accept(ctx, '组词中', { composing: true })).reason, 'composing')
  await ok('export_document', { name: 'semantic-autosave.docx' })
  assert.equal((await accept(ctx, '保存后仍可接受')).success, true, 'read-only export preserves valid snapshot')
  await ok('undo'); assert.equal(await text(), '采购方应')
  ctx = await capture()
  await ok('debug_writing_readonly', { enabled: true })
  assert.equal((await accept(ctx, '只读误改')).reason, 'readonly')
  assert.equal((await exec('capture_writing_context')).reason, 'readonly')
  await ok('debug_writing_readonly', { enabled: false })
  assert.equal(await text(), '采购方应')
  console.log('PASS bounds, explicit composition guard, autosave and comparison read-only guard')

  await reset('技术服务合同\n第一条 价款\n合同总价为人民币120000元。\n合同总价为人民币\n附件一 专用合同\n第一条价款\n合同总价为人民币10000元。\n合同总价为人民币')
  ctx = await capture()
  assert.equal(ctx.paragraphIndex, 7)
  assert.equal(ctx.scopeKnown, true)
  assert.deepEqual(ctx.sectionPath, ['附件一', '第一条'])
  assert.equal(ctx.sectionTitle, '附件一 / 第一条', 'plain headings without OutlineLevel retain appendix namespace')
  await ok('select_paragraph', { index: 3 }); await ok('collapse_selection', { to: 'end' })
  ctx = await capture()
  assert.equal(ctx.paragraphIndex, 3)
  assert.deepEqual(ctx.sectionPath, ['第一条'])
  assert.equal(ctx.sectionTitle, '第一条', 'moving back to main contract restores its own scope')
  await ok('find_replace', { findText: '附件一', replaceText: '附件二', __agent: true })
  await ok('set_revision_view', { mode: 'all' }); await ok('goto', { type: 'end' })
  ctx = await capture()
  const finalBody = await ok('get_document_text', { __agent: true })
  assert.equal(finalBody.revision, ctx.revision)
  assert.equal(finalBody.paragraphs[4].text, '附件二 专用合同')
  assert.equal(ctx.sectionTitle, '附件二 / 第一条', 'source snapshot and scope both use final text despite visible deletion revisions')
  await reset('无标题的当前正文')
  ctx = await capture()
  assert.equal(ctx.sectionTitle, '正文')
  assert.equal(ctx.scopeKnown, true, 'known body with no headings is different from unknown scope')
  console.log('PASS real paragraph scope and plain-text appendix/article namespace')
} finally {
  await browser.close()
  await new Promise(r => server.close(r))
}
