CREATE TABLE IF NOT EXISTS work_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL,
    branch_name VARCHAR(128) NOT NULL,
    started_at TIMESTAMP(6) NOT NULL,
    ended_at TIMESTAMP(6),
    status VARCHAR(16) NOT NULL,
    title VARCHAR(256),
    user_id BIGINT NOT NULL
);
