// SPDX-FileCopyrightText: 2026 北京京微资易科技有限公司 and AI WorkDeck contributors
// SPDX-License-Identifier: AGPL-3.0-or-later
import test from 'node:test'
import assert from 'node:assert/strict'
import { JSDOM } from 'jsdom'
import { attachSemanticWritingPanel } from '../../src/composables/semanticWritingPanel.js'
const tick=()=>new Promise(r=>setTimeout(r,5))
function fixture(t){
  const dom=new JSDOM('<html><head></head><body><canvas></canvas><textarea></textarea></body></html>',{pretendToBeVisual:true});const doc=dom.window.document
  const calls=[],sent=[],listeners=new Set();let result={view:{id:'j',status:'READY',profileLabel:'尽调报告与法律意见书',facts:[{id:'f',sourceId:'src',quote:'材料原话：<img src=x onerror=alert(1)>',label:'取得状态',value:'未取得'}],sources:[{id:'src',name:'合成资料',version:'V2',locator:'第2页',text:'原文'}],advice:[{text:'相关事项尚待核实。',factIds:['f'],sourceIds:['src'],explanation:'材料尚未取得'}]},notices:[]}
  function emit(m){for(const l of listeners)l(m)}
  const transport={subscribe:l=>{listeners.add(l);return()=>listeners.delete(l)},send:m=>{sent.push(m);if(m.type!=='writing-request')return;calls.push(m);const r=m.action==='semantic-settings'?{stance:'收购方',cutoffDate:'2026-09-15',files:[1,2,3,4,5].map(id=>({id,name:`合成材料${id}`}))}:m.action==='semantic-generate'?result:m.action==='semantic-accept'?{applied:true,message:'已采用，可撤销。'}:{};queueMicrotask(()=>emit({type:'writing-response',session:m.session,id:m.id,result:r}))}}
  const panel=attachSemanticWritingPanel({canvas:doc.querySelector('canvas'),input:doc.querySelector('textarea'),transport,focus:()=>{}})
  emit({type:'writing-config',config:{session:'session-1',writable:true}})
  t.after(()=>{panel.destroy();dom.window.close()})
  return {doc,calls,sent,panel,dom,emit,setResult:r=>{result=r},
    states:()=>sent.filter(m=>m.type==='semantic-writing-state'),
    root:()=>doc.querySelector('.awd-semantic'),sheet:()=>doc.querySelector('.awd-semantic-sheet'),
    button:text=>[...doc.querySelectorAll('button')].find(b=>b.textContent===text),
    // 唯一入口在宿主工具栏（dev-board#748）：客体里不再有那颗固定按钮。
    async open(){emit({__lo:'lo-relay',type:'semantic-writing-panel',open:true});await tick()},
    async close(){emit({__lo:'lo-relay',type:'semantic-writing-panel',open:false});await tick()}}
}
test('visible entry opens choices without automatically calling a model',async t=>{const f=fixture(t);await f.open();assert.equal(f.calls.length,1);assert.equal(f.calls[0].action,'semantic-settings');assert.equal(f.doc.querySelectorAll('select option').length,4);assert.ok(f.button('续写一句'));assert.ok(f.button('改写选区'))})
test('materials selection prevents a fifth checked source',async t=>{const f=fixture(t);await f.open();const boxes=[...f.doc.querySelectorAll('input[type=checkbox]')];assert.equal(boxes.length,5);for(const b of boxes.slice(0,4)){b.click()}assert.equal(boxes[4].disabled,true);boxes[0].click();assert.equal(boxes[4].disabled,false)})
test('composition blocks model trigger',async t=>{const f=fixture(t);await f.open();f.doc.querySelector('textarea[data-semantic-stance]').dispatchEvent(new f.dom.window.CompositionEvent('compositionstart',{bubbles:true}));f.button('续写一句').click();await tick();assert.equal(f.calls.some(c=>c.action==='semantic-generate'),false)})
test('suggestion preview uses safe text nodes and exact cited quote',async t=>{const f=fixture(t);await f.open();f.button('续写一句').click();await tick();assert.ok(f.doc.body.textContent.includes('相关事项尚待核实。'));assert.ok(f.doc.body.textContent.includes('材料原话：<img src=x onerror=alert(1)>'));assert.equal(f.doc.querySelectorAll('img').length,0);assert.ok(f.button('采用这条'))})
test('stale context removes accept action',async t=>{const f=fixture(t);await f.open();f.button('续写一句').click();await tick();f.emit({type:'writing-config',config:{session:'session-1',semantic:{state:'STALE'}}});assert.equal(f.button('采用这条'),undefined);assert.ok(f.doc.body.textContent.includes('重新生成'))})
test('cursor movement cancels a pending or ready suggestion',async t=>{const f=fixture(t);await f.open();f.button('续写一句').click();await tick();f.panel.cursorMoved({reason:'move'});await tick();assert.ok(f.calls.some(c=>c.action==='semantic-cancel'));assert.equal(f.button('采用这条'),undefined)})
test('EMPTY response explains insufficient basis rather than success',async t=>{const f=fixture(t);await f.open();f.setResult({view:{status:'EMPTY',advice:[],warnings:['缺少材料']},notices:[]});f.button('续写一句').click();await tick();assert.ok(f.doc.body.textContent.includes('没有足够依据'));assert.equal(f.button('采用这条'),undefined)})
test('settings save sends explicit stance and cutoff only',async t=>{const f=fixture(t);await f.open();f.doc.querySelector('[data-semantic-stance]').value='投资方';f.button('保存项目设置').click();await tick();const call=f.calls.find(c=>c.action==='semantic-save-settings');assert.deepEqual(call.data,{stance:'投资方',cutoffDate:'2026-09-15'})})
test('local EMPTY still shows attributed material excerpts',async t=>{const f=fixture(t);await f.open();f.setResult({view:{status:'EMPTY',facts:[{id:'f',sourceId:'s',label:'取得状态',value:'未取得',quote:'原件未取得'}],sources:[{id:'s',name:'合成材料',locator:'第3项',version:'very-long-internal-hash'}],advice:[]},notices:[]});f.button('读取事实').click();await tick();assert.ok(f.doc.body.textContent.includes('资料摘录'));assert.ok(f.doc.body.textContent.includes('原件未取得'));assert.ok(f.doc.body.textContent.includes('第3项'));assert.equal(f.doc.body.textContent.includes('very-long-internal-hash'),false)})
test('stance input follows service maximum',async t=>{const f=fixture(t);await f.open();assert.equal(f.doc.querySelector('[data-semantic-stance]').maxLength,120)})
test('new document session clears selected materials and previous settings',async t=>{const f=fixture(t);await f.open();f.doc.querySelector('input[type=checkbox]').click();f.emit({type:'writing-config',config:{session:'new-document',writable:true}});assert.equal(f.doc.querySelector('.awd-semantic-sheet').hidden,true);assert.equal(f.doc.querySelector('[data-semantic-stance]').value,'');await f.open();assert.equal(f.doc.querySelectorAll('input:checked').length,0)})
test('composition beginning while acceptance is in flight cancels the stale candidate',async t=>{const f=fixture(t);await f.open();f.button('续写一句').click();await tick();f.button('采用这条').click();f.doc.querySelector('textarea').dispatchEvent(new f.dom.window.CompositionEvent('compositionstart',{bubbles:true}));await tick();assert.ok(f.calls.some(c=>c.action==='semantic-cancel'));assert.equal(f.panel.isComposing(),true);assert.equal(f.doc.body.textContent.includes('已采用，可撤销。'),false)})
test('saving settings disables generating until the save completes',async t=>{const f=fixture(t);await f.open();f.button('保存项目设置').click();assert.equal(f.button('续写一句').disabled,true);f.button('续写一句').click();assert.equal(f.calls.some(c=>c.action==='semantic-generate'),false);await tick();assert.equal(f.button('续写一句').disabled,false)})
test('material excerpts display evidence state and party role without claiming verification',async t=>{const f=fixture(t);await f.open();const statuses=['PENDING','CONFLICT','MISSING','CLAIM','COUNTERPARTY_PROPOSAL','DOCUMENT_STATES','CONTRACT_TERM'];f.setResult({view:{status:'EMPTY',facts:statuses.map((status,index)=>({id:String(index),sourceId:'s',label:'金额',value:'120000元',status,role:index===3?'原告':''})),sources:[{id:'s',name:'合成材料'}],advice:[]}});f.button('读取事实').click();await tick();for(const text of ['条件待确认','资料有分歧','材料未取得','当事人主张','对方稿','材料记载','原告'])assert.ok(f.doc.body.textContent.includes(text),text);assert.equal(f.doc.querySelector('.awd-semantic-card').textContent.includes('已核实事实'),false)})
test('the guest keeps no floating launch button on the canvas',async t=>{const f=fixture(t);assert.equal(f.doc.querySelector('.awd-semantic-launch'),null);assert.equal(f.button('语义补全'),undefined);assert.equal(f.root().hidden,true,'关着时根节点不占画布也不接点击');await f.open();assert.equal(f.root().hidden,false);assert.equal(f.sheet().hidden,false)})
test('the host toolbar message opens and closes the sheet',async t=>{const f=fixture(t);await f.open();assert.equal(f.sheet().hidden,false);assert.ok(f.calls.some(c=>c.action==='semantic-settings'));await f.close();assert.equal(f.sheet().hidden,true);assert.equal(f.root().hidden,true)})
test('availability and open state are reported back to the host',async t=>{const f=fixture(t);assert.deepEqual(f.states().at(-1),{__lo:'lo-relay',type:'semantic-writing-state',available:true,open:false});await f.open();assert.equal(f.states().at(-1).open,true);f.button('关闭').click();await tick();assert.deepEqual(f.states().at(-1),{__lo:'lo-relay',type:'semantic-writing-state',available:true,open:false});assert.equal(f.sheet().hidden,true)})
test('a read-only or switched document reports the entry as unavailable',async t=>{const f=fixture(t);await f.open();f.emit({type:'writing-config',config:{session:'session-1',writable:false}});await tick();assert.equal(f.states().at(-1).available,false);assert.equal(f.states().at(-1).open,false);assert.equal(f.sheet().hidden,true);await f.open();assert.equal(f.sheet().hidden,true,'不可用时宿主消息也打不开')})
